### ISSUE TITLE
Support for kernelSU

### ISSUE THREAD

**Issue by scientiac** [nitanmarcel/isodrive-magisk#5]
Since kernelSU is getting traction and it's easier and safer than Magisk (if the Custom Rom has prebuilt support for it). It would be great to have this as a [kernelSU](https://kernelsu.org/) module as well.

**Comment by nitanmarcel** [comment]
Magisk modules are compatible with KernelSU by default

**Comment by capsudo** [comment]
It does not work on KernelSU next, after installing module and rebooting, the isodrive command is still not found (tried in su)

**Comment by nitanmarcel** [comment]
> It does not work on KernelSU next, after installing module and rebooting, the isodrive command is still not found (tried in su)

I've noticed this, but didn't paid attention to it since I'm planning to do an app sometimes, I'm still blocked by some things https://github.com/nitanmarcel/isodrive-magisk/issues/7#issuecomment-3385231044

For now, you can unzip the module and copy the binary to `/data/local/tmp` give it executable permission and run it from there. The module will be discontinued at one point
